### ISSUE TITLE
rglqol will occasionally change map twice 

### ISSUE THREAD

**Issue by l-Aad-l** [RGLgg/server-resources-updater#15]
[9:33 PM] 24:
public Action WarnServ(Handle timer)
{
    LogMessage("[RGLQoL] An important cvar has changed. Forcing a map change in 25 seconds unless the map is manually changed before then.");
    PrintColoredChatAll("\x07FFA07A[RGLQoL]\x01 An important cvar has changed. Forcing a map change in 25 seconds unless the map is manually changed before then.");
    g_hWarnServ = null;
}

this function also creates a scenario that sometimes will change map 2ce
[9:35 PM] 24: shouldn't it be Plugin_Continue or something

**Comment by c43721** [comment]
qol should try seeing if those cvars are already set and disable this
