### ISSUE TITLE
No support for forked servers, actively breaks them.

### ISSUE THREAD

**Issue by teeklet** [RGLgg/server-resources-updater#35]
Forked servers are broken as this plugin assumes each installation has only 1 sourcemod install and it's at the default location.

If you actually try to run the plugin from another sm install you will break the default installation as the updater dumps a load of plugins into the default folder even if it's being ran from somewhere else.

https://github.com/RGLgg/server-resources-updater/blob/updater-beta/updatefile.txt
https://wiki.alliedmods.net/Multiple_or_Forked_Servers_(SourceMod)

**Comment by l-Aad-l** [comment]
Since this is both a very unique issue and that I have no real way of actually debugging/testing this myself, we'll have to wait for anyone who is able to provide an adequate solution to this via a pull request.

**Comment by teeklet** [comment]
You can recreate the issue fairly easily. Just rename the addons/sourcemod folder to something else and then launch a tf2 server with +sm_basepath "new path" as a command line option. It will attempt to update the wrong folder.

The only change needed is to make the paths in the update file relative to the sm_basepath convar rather than absolute.

**Comment by sapphonie** [comment]
this is an issue with the update file using `/addons/sourcemod/` instead of using `Path_SM`
